### ISSUE TITLE
Initial Release - Documentation - General

### ISSUE THREAD

**Issue by makubacki** [OpenDevicePartnership/patina#18]
Make sure "general" documentation is in place.

- Project overview
- First-time build setup
- Build, test, and test coverage instructions
- Implementation decisions and patterns (expect this will continue after this task as an ongoing list)
- Verify inline code documentation. Is it accurate? Does it need further detail?
- Add missing documentation. Prioritize common/fundamental areas of the code.

**Comment by Javagedes** [comment]
@makubacki do we need #79 (Videos)? I'm tempted to close.

**Comment by makubacki** [comment]
> [@makubacki](https://github.com/makubacki) do we need [#79](https://github.com/pop-project/uefi-dxe-core/issues/79) (Videos)? I'm tempted to close.

Agree. I'm closing it.
