### ISSUE TITLE
Initial Release - Release Process - crates.io publication flow

### ISSUE THREAD

**Issue by makubacki** [OpenDevicePartnership/patina#20]
GitHub workflow to publish repo releases to crates.io. Must be written to be readily extensible to other crate repos.

**Comment by Javagedes** [comment]
@makubacki Some discussion needs to be had around this process. I currently see two valid workflows:

## Sync all crates to repository release version and tags

These processes would be initiated by the maintainer via a single workflow. The only manual step by the maintainer would be to validate the current draft release is correct.

1. Locate the current draft release, error if not found
2. Identify the version in the draft release
3. Create a commit that updates all crate's Cargo.toml
4. Run `cargo publish --dry-run` to verify everything works as expected
5. Commit the update to `main`
6. Wait for the Draft Release updater to finish
7. Publish the draft Release
8. publish all crates to crates.io

**Note:** In a perfect would, we would trigger this workflow when maintainer does a release, however when this happens, the cargo.toml version update commit and thus the tag that the publish happens on, is always one commit ahead of the repo release tag. We could have the maintainer update the version manually, but that is error prone (Forgetting one crate).
 
## Publish crates asynchronously to the repo release and each other

This process would be initiated automatically whenever a commit is merged into main that updates a Cargo.toml version

1. run `cargo publish`

As you can see, this option is much simpler, however we are out of sync with the release version of the repository and thus becomes difficult to know what changes go into each version. We could try and generate a release log from the git commits, for any commit that touches the subdirectory of a crate, maybe?

**Comment by Javagedes** [comment]
Looking at bevy's release process (https://github.com/bevyengine/bevy/blob/main/.github/workflows/release.yml), I think that may be good to follow. They are similar to us in their dependencies. Looks like they keep all of their versions in lock step. I'm going to follow that for now, but we can change it if you have other opinions when you are back.

**Comment by Javagedes** [comment]
Currently working on this. Not blocked at the moment, but I'm already anticipating this blocker: we are currently on a rev for goblin because they have not completed a release for john's change. I've asked for a release to be done, but until it's done, we cannot publish, because all dependencies must be versioned and uploaded to crates.io: https://github.com/m4b/goblin/issues/423

**Comment by makubacki** [comment]
> Currently working on this. Not blocked at the moment, but I'm already anticipating this blocker: we are currently on a rev for goblin because they have not completed a release for john's change. I've asked for a release to be done, but until it's done, we cannot publish, because all dependencies must be versioned and uploaded to crates.io: [m4b/goblin#423](https://github.com/m4b/goblin/issues/423)

Sounds good. We don't need to officially publish until the open-source milestone is reached.

**Comment by Javagedes** [comment]
The workflow "flow" actually seems like it will be fairly simple if we use `cargo-release`.

I think the best way to do this is to have a workflow that a maintainer manually dispatches when they want to do a release.
 
workflow steps:
1. `cargo release --workspace` Which does a dry run by default, making sure everything builds and such
2. use gh api to grab the current draft release, getting the release version. error if there is 0 or more than one draft release.
3. `cargo release $(VERSION) -x --no-tag --no-confirm --workspace` which will create a new commit that updates all versions in all cargo.toml files to $(VERSION), publishes the crates to crates.io, then pushes the commit to the branch (which will be main)
4. Use gh api to trigger a github release, which does it's thing and also the tag for us.

@makubacki thoughts?
