### ISSUE TITLE
Initial Release - Existing Code Usage - On Latest Code?

### ISSUE THREAD

**Issue by makubacki** [OpenDevicePartnership/patina#29]
Update all code to use the latest Rust code we've already written.

Example: Is all code using the boot services and runtime services wrapper in `mu_rust_helpers` yet?

**Comment by berlin-with0ut-return** [comment]
Reviewed and decided against some possible changes:
- Moving to the `BootServices` and `RuntimeServices` wrappers in `mu_rust_helpers`: we don't really use the raw `efi::` pointers much except to assign function pointers. Also, the system table which is a ffi C struct expects them to be `efi::` types, so I don't think it's worth converting back and forth.
- Combining `tpl_mutex` implementations in the core repo and `mu_rust_helpers`. The main issue is the static boot services pointer, which we cannot refer to in the tpl_mutex struct if we want to keep constructors `const`.

I did transfer over some guid macros in `mu_rust_helpers` and use make sure they're used in the dxe core.
