### ISSUE TITLE
Initial Release - Code Organization - Decide on final locations for "Library" crates

### ISSUE THREAD

**Issue by makubacki** [OpenDevicePartnership/patina#9]
Determine whether to keep the crates, move elsewhere, how to name.

**Comment by makubacki** [comment]
Likely follow the [bevy](https://github.com/bevyengine/bevy) model - release all crates at the same time with the same version.

**Comment by Javagedes** [comment]
`Library/*` crates were moved to `crates/*` and renamed to follow a standard `uefi_*` pattern. All crates will be released together with the same release version. This was done in #101
